### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by sudo-suhas** [chrisyip/koa-pug#22]
Dependencies used in the project are outdated:
```diff
"dependencies": {
-    "fs-extra": "^0.24.0",
-    "lodash": "^3.10.1",
-    "pug": "^2.0.0-alpha6"
+    "fs-extra": "^0.30.0",
+    "lodash": "^4.16.4",
+    "pug": "^2.0.0-beta6"
   },
   "devDependencies": {
-    "bluebird": "^2.9.34",
+    "bluebird": "^3.4.6",
     "chai": "^3.2.0",
-    "cheerio": "^0.19.0",
-    "eslint": "^1.10.2",
-    "istanbul": "^0.3.19",
-    "jstransformer-markdown-it": "^0.1.0",
+    "cheerio": "^0.22.0",
+    "eslint": "^3.7.1",
+    "istanbul": "^0.4.5",
+    "jstransformer-markdown-it": "^1.0.0",
     "koa": "^1.0.0",
     "koa-route": "^2.4.2",
     "koa-vhost": "^0.5.0",
     "marked": "^0.3.5",
-    "mocha": "^2.3.0",
-    "supertest": "^1.1.0",
-    "supertest-koa-agent": "^0.2.1"
+    "mocha": "^3.1.0",
+    "supertest": "^2.0.0",
+    "supertest-koa-agent": "^0.3.0"
   },
```

However, updating all the dependencies makes it incompatible with older releases of node.js(before 4).

Also, is it a good idea to have pug as a dependency? There could be different versions being used by the project and koa-pug.

**Comment by chrisyip** [comment]
> is it a good idea to have pug as a dependency? There could be different versions being used by the project and koa-pug.

Having pug as dependency can obtain these advantages:

- Developer can install different version of pug that contains breaking changes and won't break koa-pug.
- koa-pug can keep its code more reliable and clean without detecting if APIs are available or not.

**Comment by chrisyip** [comment]
About outdated dependencies, IMO, we don't need to catch up the latest versions, because of koa and pug are still supporting node v0.12.

I've updated pug to `2.0.0-beta6` a few days ago, so I'm closing this issue.

Thank you.

**Comment by sudo-suhas** [comment]
:+1:
