### ISSUE TITLE
Can you write a pug view for egg?

### ISSUE THREAD

**Issue by popomore** [chrisyip/koa-pug#24]
it's based on https://github.com/eggjs/egg-view, we will document for it, maybe next week.

**Comment by chrisyip** [comment]
Sure, I'll write one in the next few days.

**Comment by popomore** [comment]
Thx, if you have some question, you can contact me on twitter.

**Comment by chrisyip** [comment]
https://github.com/chrisyip/egg-view-pug

**Comment by popomore** [comment]
Perfect!
