### ISSUE TITLE
Can Koa-pug render multiple blocks?

### ISSUE THREAD

**Issue by EpicHigh** [chrisyip/koa-pug#26]
```pug
//layout.pug
html
    head
        body
            block navbar
            block content
```

Navbar (navbar.pug, navbarAuth.pug)
Content (index.pug, signin.pug, signup.pug)

When I use ctx.render("index"), it render just index.pug only.

```pug
//index.pug
extends layout
    block navbar
    block content

**Comment by chrisyip** [comment]
What do you mean "render just index.pug only"? `block navbar` and `block content` not rendered?

Can you provide a more detailed example?

**Comment by EpicHigh** [comment]
"ctx.render("index")" it renders an extends of layout, and a block of content, but it doesn't render a navbar.pug which I defined block navbar. Can a render function render multiple blocks? such as ctx.render("index","navbar") or something.

**Comment by EpicHigh** [comment]
Sorry for the inconvenience, I just misunderstood about an extend and a block.
