### ISSUE TITLE
TypeScript error on koa import

### ISSUE THREAD

**Issue by epx-nathan** [chrisyip/koa-pug#28]
When running `tsc` I get the following error:

<img width="1088" alt="Screen Shot 2019-12-16 at 11 31 52 AM" src="https://user-images.githubusercontent.com/55513121/70929172-14d3d980-1ff8-11ea-90a4-74977de246a8.png">

If I update the import statement in the referenced dist file (koa-pug/dist/index.d.ts) to `import * as Koa from 'koa'` the error goes away.

I'm using the following package versions:

* koa-pug: 4.0.2
* koa: 2.11.0
* @types/koa: 2.11.0

https://github.com/chrisyip/koa-pug/blob/94bcae17acb1a4e768ad8865063386eb297faa93/source/index.ts#L3

I don't know much about Typescript, but if you were able to update your import signature for Koa, I assume that would fix this issue for me and for anyone else who might have it. Also open to a different solution for resolving this issue!

Let me know if there are any further details I can provide.

Thanks!

**Comment by chrisyip** [comment]
Fixed, please update koa-pug to 4.0.3.

FYI, `koa-pug` requires `typescript@^3.2`.

**Comment by epx-nathan** [comment]
Thanks so much!
