### ISSUE TITLE
Exposing locals to layout

### ISSUE THREAD

**Issue by Dronar** [chrisyip/koa-pug#33]
I'm having issues sending a local variable from a pug file to it's layout file. I'm not sure if this is an issue in koa-pug or in pug but I'll start here.

### Working Example
layout.pug
```
block vars
p #{foo}
```
file.pug
```
extends layout.pug
block vars
  - var foo = 'bar'
```
This will print `<p>bar</p>`

### Not working Example
layout.pug
```
block vars
p #{foo}
```
file.pug
```
extends layout.pug
block vars
  - var foo = baz
```
controller.js
```
await ctx.render('file', {baz: 'bar'});
```
This will print `<p></p>`

**Comment by chrisyip** [comment]
Tried with koa-pug@4.0.4, it seems working fine, need more details.

![image](https://user-images.githubusercontent.com/189559/93763524-35def000-fc44-11ea-991e-3dbe425e81bb.png)

**Comment by Dronar** [comment]
Ah, it seems my example in here was a bit over simplified. The code provided does indeed work.
It does not work if the local and the variable has the same name, but that's something of an edge case and easy to avoid.

If you change index.js to `await ctx.render('main', {foo: 'bar'})` and main.pug to `var foo = foo` you should see what I'm seeing :)

**Comment by chrisyip** [comment]
Oh, it's a bug in pug@2.

In pug@2, `- var foo = foo` will be compiled to something like this:

```js
const compiler = function (locals) {
  var foo = foo; // It's legal in JavaScript, `foo` will be `undefined`
  ...
  return '<p>' + pug.escape(foo) + '</p>' // `foo` will become an empty string after escaped
})())
```

This bug was fixed in pug@3, I'll be releasing a new version to fix it when I have time.

**Comment by Dronar** [comment]
Ok, it's all good then I suppose. Thanks for taking the time to look into this!
