### ISSUE TITLE
Please upgrade lodash

### ISSUE THREAD

**Issue by arnaudbuchholz-sap** [chrisyip/koa-pug#57]
koa-pug is based on lodash.forin (as well as other lodash extracts) made with version 4.4.0 and is subject to many vulnerabilities (see https://github.com/lodash/lodash/issues/5808).

Is there a chance you could use the latest version of lodash (4.17.21) instead ?

**Comment by chrisyip** [comment]
Sorry for the late response. This issue was fixed in `v5.1.1`, which was also released.

**Comment by arnaudbuchholz-sap** [comment]
awesome, thx !
